version: "3"

services:
  db:
    image: postgres
    # ports:
    #   - "5432:3306"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "postgres"

  server:
    build: ../todo_app
    command: bash -c "python manage.py makemigrations && python manage.py migrate && python manage.py runserver 0.0.0.0:8000"
    ports:
      - "8000:8000"
    depends_on:
      - db
    links:
      - db

  web:
    build: .
    ports:
      - "3000:3000"
